### PR TITLE
Add Visible

### PR DESCRIPTION
**Pull request by metametapod**
This one is less recent, but the opt-out window is still in effect.

### CODE REVIEW

**Comment by lynnpepin** [comment]
This one I'm not so sure about...

It looks like Dispute Resolution Section 6 allows customers to opt out of arbitration *only in the event* that 50 or more customers enter notice of dispute.

Other than that, what they _do_ say is

> BUT IF YOU WISH TO PRESERVE YOUR RIGHT TO BRING AN ARBITRATION OR SMALL CLAIMS CASE REGARDING SUCH DISPUTE, YOU MUST WRITE TO US AT [VISIBLEARBITRATIONS@VISIBLE.COM](mailto:VISIBLEARBITRATIONS@visible.com), IF YOU DO NOT NOTIFY US IN WRITING OF SUCH DISPUTE WITHIN THE 180-DAY PERIOD, YOU WILL HAVE WAIVED YOUR RIGHT TO DISPUTE THE CHARGE(S) AND TO BRING AN ARBITRATION OR SMALL CLAIMS CASE REGARDING ANY SUCH DISPUTE.

Which is pretty awful. Visible by Verizon has one of the most egregious arbitration clauses I've seen.

- You can't opt out,
- the ToS _only allows for arbitration_ to start disputes,
- AND the ToS only allows arbitration within 180 days of the disputed charge.
- Opting-out of arbitration is only permitted in specific cases, and only after arbitration has started.


It looks like some Redditors ([example one](https://www.reddit.com/r/Visible/comments/z89uzy/psa_dont_swap_sim_or_redownload_esim_for_unlock/) and [example two](https://www.reddit.com/r/Visible/comments/z683em/visible_sucks_3_separate_payment_methods_dont/) and [example three](https://www.reddit.com/r/Visible/comments/17n22dj/issue_porting_from_tmobile_into_visible_for/)) have run into problems with Visible. It seems like the standard route is to file arbitration disputes _and_ FCC complaints _and_ BBB reviews simultaneously. 

I'm going to do some more research, but as far as I can tell, there is no general opt-out provision :(

**Comment by metametapod** [comment]
Good point, I misread the dispute instructions as being an opt-out process. Maybe this would be a better fit for the wall of shame list.

**Comment by lynnpepin** [comment]
For sure-- going to keep this up for a bit while I do some research though. I do appreciate the work though :)

**Comment by lynnpepin** [comment]
I appreciate all the work you've been doing for this project :)  But it does seems definite that Visible does not provide for arbitration opt-out. ;( So I'll go ahead and close this PR.

**Pull request closed without merging**
